Add basic issue templates
accentor/web pull request #309
Opened 2020-10-13 16:15 UTC by robbevp

Adds a basic issue template. This is strongly based on github's default - I guess we'll update and improve as we go along?

re #303

2020-10-13 16:33 UTC, robbevp commented
We might want to create a separate one for questions? I don't think we can expect everyone to jump into the matrix channel. Or can we add the discussion tab like [vuetify](https://github.com/vuetifyjs/vuetify/discussions)?

2020-11-01 13:26 UTC, charvp requested changes

2020-11-01 13:26 UTC, charvp commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: bug_triage
Just `bug`, I think.

2020-11-01 13:26 UTC, charvp commented on .github/ISSUE_TEMPLATE/feature_request.md
> +labels: feature_request
We use `enhancement` in the accentor repos.

2020-11-01 13:29 UTC, charvp commented
> We might want to create a separate one for questions? I don't think we can expect everyone to jump into the matrix channel. Or can we add the discussion tab like [vuetify](https://github.com/vuetifyjs/vuetify/discussions)?

I don't like handling questions in GitHub issues. The matrix channel should be accessible to guests, so I don't think people even need to create an account. The discussions tab is a GitHub beta feature, so this can't be enabled (yet). Once it goes into public beta I don't have any qualms about adding it.

2020-11-01 15:31 UTC, charvp approved these changes

2020-11-01 15:31 UTC, merged