Improve reordering of TrackArtists
accentor/web pull request #380
Opened 2020-12-13 11:03 UTC by robbevp

# Description

This PR brings two improvements to the way TrackArtists can be ordered.

## Drag and drop
I've added drag and drop support, so the user can quickly move an artist multiple steps (Especially relevent for tracks with many artists).
This only works through the drag-icon and is disabled if the length of TrackArtists is exactly one.

## Keypress controls
Currently the user has to tab multiple times to go past the controls (something which annoys me a lot).
To improve the UX if created one element around all the buttons with a few keypress events to control teh order.
A user can move the artist with ArrowUp, ArrowDown and U (for up) and D (for down).
A user can delete the artist through delete or backspace.

This does mean that there is no way to focus on the individual buttons. If this is necessary (but IMHO it isn't) we could allow the user to enter this level by pressing enter (and esc to leave).

(Do note that there is no way for a new user to know these things. I like the way how Hey gives this information, but this wouldn't fit our current UI.)

## Other small improvements
* Better spacing for order controls
* The EditTrack form is only shown after the track is loaded, to prevent a quick flash of the form in its empty state before the track is loaded 

# How Has This Been Tested?

Tested in chrome 87 and FF 83 on macOS, both for EditTrack page and MassEditDialog component

2020-12-23 08:58 UTC, charvp commented
> # Description
> 
> This PR brings two improvements to the way TrackArtists can be ordered.
> ## Drag and drop
> 
> I've added drag and drop support, so the user can quickly move an artist multiple steps (Especially relevent for tracks with many artists).
> This only works through the drag-icon and is disabled if the length of TrackArtists is exactly one.
> ## Keypress controls
> 
> Currently the user has to tab multiple times to go past the controls (something which annoys me a lot).
> To improve the UX if created one element around all the buttons with a few keypress events to control teh order.
> A user can move the artist with ArrowUp, ArrowDown and U (for up) and D (for down).
> A user can delete the artist through delete or backspace.
> 

> 
> (Do note that there is no way for a new user to know these things. I like the way how Hey gives this information, but this wouldn't fit our current UI.)
> ## Other small improvements
> 
>     * Better spacing for order controls
> 
>     * The EditTrack form is only shown after the track is loaded, to prevent a quick flash of the form in its empty state before the track is loaded
> 
> 
> # How Has This Been Tested?
> 
> Tested in chrome 87 and FF 83 on macOS, both for EditTrack page and MassEditDialog component

2020-12-23 08:58 UTC, charvp commented
Sorry, wrong button.

2020-12-23 09:01 UTC, charvp requested changes
> This does mean that there is no way to focus on the individual buttons. If this is necessary (but IMHO it isn't) we could allow the user to enter this level by pressing enter (and esc to leave).

I like to edit with only keyboard controls, so this does seem like a requirement for me. To be honest, I don't see the use for the extra keyboard controls. The drag and drop is nice though.

2020-12-23 09:48 UTC, robbevp commented
> > This does mean that there is no way to focus on the individual buttons. If this is necessary (but IMHO it isn't) we could allow the user to enter this level by pressing enter (and esc to leave).
> 
> I like to edit with only keyboard controls, so this does seem like a requirement for me. To be honest, I don't see the use for the extra keyboard controls. The drag and drop is nice though.

Have you tried editing a few tracks with the keyboard controls? There might be some adjustment time, but I found that the new keyboard controls allow me to edit faster since (1) I don't have to tab through up, down, delete for each artist (2) it's a lot easier to move an artist multiple places since the keyboard focus follows the artist you are moving.
If you disagree, I'll add a way to focus on the individual buttons

2021-07-10 16:07 UTC, chvp approved these changes

2021-07-10 16:07 UTC, chvp commented on src/views/tracks/EditTrack.vue
> +        <VForm v-model="isValid" @submit.prevent="submit" v-if="loaded">
Try to refrain from fixing multiple issues in one pull request in the future.

2021-07-10 16:08 UTC, chvp approved these changes

2021-07-10 16:10 UTC, merged