Fix TopList readability
accentor/web pull request #685
Opened 2021-12-29 14:14 UTC by robbevp

Fixes an issue where only part of the count was readable. I ended up placing a second count behind the bar in black. Since we don't know the width of the bar (in pixels) or the length of the count (in pixels), this seemed like the easier solution to me.

To avoid having to change this for three different places, I also extracted the list to a separate `TopList`-component.

<img width="432" alt="Screenshot 2021-12-29 at 15 12 52" src="https://user-images.githubusercontent.com/48474670/147671073-39897a83-2f2d-47d9-bea2-05d22037954b.png">

2021-12-31 14:03 UTC, chvp requested changes
I'm not a huge fan of the text changing color all of a sudden. Ironically, this doesn't really improve readability for me. I've pushed a patch which gives the following result:
![screenshot_2021-12-31-145908](https://user-images.githubusercontent.com/42220376/147827185-bd54af39-ef12-4673-8757-0a279cc02b79.png)
Even though this could still give problems for very long text, I would argue that this wouldn't happen in practice.

2022-01-04 08:53 UTC, robbevp commented
If we go for your design, I'd put the label always on the right of the bar, rather than having this determined by the width.

2022-01-04 11:49 UTC, chvp commented
Sure, that's also a possibility.

2022-01-15 09:23 UTC, robbevp commented
@chvp Thinking about this again. Your solution will be a lot easier than my last suggestion (since then the width of the first item will vary based upon the length of the string behind it. So I'm good with merging this in its current state

2022-01-15 09:32 UTC, chvp approved these changes

2022-01-15 09:32 UTC, merged