Allow play stats for artist
accentor/web pull request #686
Opened 2021-12-30 09:26 UTC by robbevp

Allow the user to see their play stats per artist.

The layout of the stats page stays the same, just with filtered plays/tracks. Plays are currently only filtered based on the track_artists.

To access this page, I added a stats icon to the `ArtistActions`. I'm unsure if this needs to be shown in both the card and on the artist page, both left it like this for now.

Some screenshots showing all visual changes:
<img width="1385" alt="Screenshot 2021-12-30 at 10 15 24" src="https://user-images.githubusercontent.com/48474670/147738853-0b4eee98-6160-4d68-bb6c-5330e977f1ce.png">
<img width="284" alt="Screenshot 2021-12-30 at 10 16 07" src="https://user-images.githubusercontent.com/48474670/147738857-0b5a17aa-5437-4db7-90ac-d0d1fcb054a4.png">
<img width="499" alt="Screenshot 2021-12-30 at 10 16 14" src="https://user-images.githubusercontent.com/48474670/147738861-0fa8f1ce-fcc2-43aa-ad1a-26e2cd183ecd.png">
<img width="383" alt="Screenshot 2021-12-30 at 10 24 57" src="https://user-images.githubusercontent.com/48474670/147738862-587c21da-12af-4274-994a-e5c2ec35e7f1.png">

2021-12-31 13:37 UTC, chvp requested changes
I would not show this on the card. It's not that much of a primary action, IMO.

2022-01-04 13:44 UTC, robbevp commented
I've updated this to only show the stats button on the artist's page

2022-01-15 09:44 UTC, chvp requested changes
I get the following warning in the console:
```
[Vue warn]: Invalid prop: type check failed for prop "extended". Expected Boolean, got String with value "true".

found in

---> <ArtistActions> at src/components/ArtistActions.vue
       <Artist> at src/views/artists/Artist.vue
         <VMain>
           <App> at src/views/App.vue
             <VApp>
               <Main> at src/Main.vue
                 <Root>
```

Also, this is for a separate issue/PR, but we need better content if there are no plays for the selected period. I selected an artist I know I listen a lot to, but haven't listened to in the past week, and thought this was broken until I figured out I had to change the period.

2022-01-15 09:44 UTC, chvp commented on src/locales/nl.json
>  		"percentageLibraryPlayed": "Percentage van muziekbibliotheek dat je besluisterd hebt:",
```suggestion
		"percentageArtistPlayed": "Percentage van {artist} dat je beluisterd hebt:",
		"percentageLibraryPlayed": "Percentage van muziekbibliotheek dat je beluisterd hebt:",
```

2022-01-15 10:28 UTC, robbevp commented
> I get the following warning in the console:
> 
> ```
> [Vue warn]: Invalid prop: type check failed for prop "extended". Expected Boolean, got String with value "true".
> 
> found in
> 
> ---> <ArtistActions> at src/components/ArtistActions.vue
>        <Artist> at src/views/artists/Artist.vue
>          <VMain>
>            <App> at src/views/App.vue
>              <VApp>
>                <Main> at src/Main.vue
>                  <Root>
> ```
> 
> Also, this is for a separate issue/PR, but we need better content if there are no plays for the selected period. I selected an artist I know I listen a lot to, but haven't listened to in the past week, and thought this was broken until I figured out I had to change the period.

Fixed this warning (and create an issue to track the "empty" state of the stats page

2022-01-15 11:16 UTC, chvp approved these changes

2022-01-15 11:16 UTC, merged